[workspace]
resolver = "2"
members = [
    "mines",
    "langton",
    "gameoflife"
]

[workspace.package]
version = "1.0.0"
edition = "2021"

[workspace.dependencies]
ndarray = "0.15.6"
crossterm = "0.27.0"
rand = "0.8.5"
